### ISSUE TITLE
PHP Warning:  Undefined array key "HTTP_ACCEPT" in lib/plugins/dokusioc/action.php on line 418

### ISSUE THREAD

**Issue by StarArmy** [mprins/dokuwiki-plugin-dokusioc#17]
When running Dokuwiki in PHP 8.2 the plugin generates errors in my logs, is the plugin PHP8 compatible?

This is the item I'm seeing:

`PHP Warning:  Undefined array key "HTTP_ACCEPT" in lib/plugins/dokusioc/action.php on line 418`

**Comment by mprins** [comment]
>  is the plugin PHP8 compatible?

yes
